<!doctype html>
<html lang="en"> 
 <head> 
  <meta charset="UTF-8"> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <link rel="stylesheet" href="movie.css"> 
  <link rel="stylesheet" href="https://drive.google.com/uc?id=1a1MM7wk_zWu46sMcokC44BZLt_bA5agL">
  <title>MARVEL film</title> 
 </head> 
 <body> 
  <header> <!-- problem--> 
   <div class="mic_dot"> 
    <div class="mic"></div> 
    <div class="dot"></div> 
   </div> 
   <nav> 
    <h3 class="brand">Marvel</h3> 
    <ul> 
     <li><a href="#">Home</a></li> 
     <li><a href="#">Trending</a></li> 
    </ul> 
    <div class="search"> 
     <input type="text" placeholder="Search..."> 
    </div> 
   </nav> <!-- section start--> 
   <section> 
    <img src="https://dl7.wapkizfile.info/download/c673ee04262057ac579a559d4d599688/cab08b23b062b86168ce96214af26d89/filmy4wap+wapkiz+com/KGF%20Chapter%202%20(2022)%20New%20South%20Blockbuster%20Movie%20Hindi%20Dubbed%20Full%20HD%20480p%20720p%201080p%20ESub.jpg"> 
   </section> 
   <div class="movieinfo"> 
    <h>
         ğŸ‘‡Movie informationğŸ‘
        <br>
         <span>
        <br>
      Name =  Thor Love and Thunder (2022) MCU Hollywood Hindi Full Movie PreDvD
      <br>
      Genre =  Action/Adventure
      <br>
      Duration = Â 1h 52mint
      <br>
      Release Date = Â 2022
      <br>
      Language = Â Hindi
      <br>
      Size =Â 450mb 750mb 1.1Gb 2Gb PreDvD
      
      </span>
      <br>
      <br>
      <br>
      ğŸ‘‡Movie Download linkğŸ‘‡
    </h>
   </div> 
   
   <div class="link">
      <span>
          <br>
   <a href="https://www.mediafire.com/file/99asbavlamrq4xv/3f4ddebb6b75e94e3f0159561834445f/file?dkey=sxh8mrqynph&r=1200"> 480p Movie download</a> 
 
       <br>
       <br>
       <br>   
   <a href="https://www.mediafire.com/file/bghrca6esyxjact/bd6687425bdb1fea4ab0e26863ca0fdc/file?dkey=45m5sc6bv5g&r=1679"> 720p Movie download</a> 
       <br>
       <br>
       <br>  
   <a href="https://www.mediafire.com/file/qezxf5fg5fmg5a8/b9c6661f5a3380314c1b181877129fc0/file?dkey=hltbzhf94fw&r=1659"> 1080p Movie download</a> 
   </span>
   </div> 
   <div class="screenshort">
       
<img src="https://i2.imgfastcdn.xyz/pix/2022/05/16/72c5b0e93856ef32f38169ed1aff92e6.jpg" alt="Thor Love and Thunder screenshort">
   </div>
   
  </header> 
 </body>
</html>
